# Automatically generated by configure - do not modify
SRC_PATH=/home/xiaosatianyu/workspace/git/afl-yyy/qemu_mode/qemu-2.3.0/roms/vgabios
AS=as
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
